service: serverless-nestjs-whitelabel

plugins:
  - serverless-offline
  - serverless-optimize-plugin

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-linux-arm64-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-openssl-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'

functions:
  main:
    handler: dist/src/serverless.handler
    events:
      - http:
          cors: true
          method: ANY
          path: /
      - http:
          cors: true
          method: ANY
          path: '{proxy+}'
  db-migrate:
    handler: dist/src/serverless.migrate.handler